### ISSUE TITLE
Cannot find module 'b64-to-image'

### ISSUE THREAD

**Issue by ns16** [riteshgandhi/b64-to-image#1]
I successfully installed library using npm

```
npm i -S b64-to-image
```

But when I required it, I get error

```
Error: Cannot find module 'b64-to-image'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ns16/projects/viscur/typography/server-proxy/index.js:107:20)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

I have 11.10.1 node.js version and 6.7.0 npm version.

**Comment by riteshgandhi** [comment]
Hi,

below is the example. note the require statement. the readme has incomplete syntax

const base64ImageDecoder = require('b64-to-image**/b64-to-image**');
 
// valid base64 string
let base64String = '"data:image/png;base64,iVBORw0...."'
base64ImageDecoder.convert(base64String, 'output\\images', 'testImage')
    .then(result => {console.log(result);})
    .catch(err => console.error(err));

**Comment by ns16** [comment]
It works for me

```
const base64ImageDecoder = require('b64-to-image/b64-to-image');
```

**Comment by riteshgandhi** [comment]
great. closing the issue
